### ISSUE TITLE
Create CI pipeline with unit tests and attach it to PR checks

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/e-structures#1]
There is no pipeline in this repo to run unit tests automatically on PR.

**Comment by rafzei** [comment]
@mkyc can we use the same approach as for modules pipeline or there is another idea?

**Comment by przemyslavic** [comment]
A pipeline has been created to automatically run unit tests for the e-structures module.
The results are shown in the `Azure DevOps` dashboard and in the `Checks` tab for the given PR in GitHub.
