### ISSUE TITLE
Consider smarter way of validating fields

### ISSUE THREAD

**Issue by mkyc** [epiphany-platform/e-structures#3]
**Is your feature request related to a problem? Please describe.**
Current validation process is manual code. 

**Describe the solution you'd like**
This would be good to have some validation rules provided directly in struct tags and not in separate function. 

**Describe alternatives you've considered**
In case of very custom validations, some logic might stay in separate function. 

**Additional context**

> Maybe something to consider later is to use some smarter way of validating the fields? Just first result on Google something like this:
> 
> https://github.com/go-validator/validator
> 
> _Originally posted by @seriva in https://github.com/epiphany-platform/e-structures/pull/2#discussion_r556514903_

**Comment by erzetpe** [comment]
Those links may be also useful for evaluation of go-validator tool:
https://medium.com/tunaiku-tech/go-validator-v10-c7a4f1be37df
https://github.com/go-playground/validator/tree/v10.4.1
https://pkg.go.dev/gopkg.in/go-playground/validator.v10

**Comment by mkyc** [comment]
go-playground validator was introduced in PR #7 

Just as additional comments for future: 
 * it's worth to be aware that this library introduces lots of external dependencies
 * validation tags are bit of magic and their syntax rather not very expressive
 * possibility to register your own validator is really nice

In general I believe that if validation rules will cause any issue it should be evaluated again if that isn't better to have internal validator written slightly better but without external dependencies.

**Comment by rpudlowski93** [comment]
Tested and validation works great! 
Only two suggestions from my side: 
- Change the type of disk_size to INT here: [link](https://github.com/epiphany-platform/e-structures/blob/a02b88f85315c5c049588f7653e101e14bbd564a/azks/v0/azks_v0.go#L40)
- Add min=1 to validation in name field, here: [link](https://github.com/epiphany-platform/e-structures/blob/a02b88f85315c5c049588f7653e101e14bbd564a/azbi/v0/azbi_v0.go#L46)

**Comment by mkyc** [comment]
Upgraded in #13

**Comment by przemyslavic** [comment]
✔ Fixed the validations for the `name` parameter (added `min` length `=1`) and changed the validation for the disk size from `string` to `integer`.
